---
abstract: 'Yet another approach for polymorphism.'
author:
  - 'lieutar <lieutar@1dk.jp>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Data-Polymorph
no_index:
  directory:
    - inc
    - t
requires:
  Scalar::Util: 0
version: 0.01
